apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/hoanglecao/gitopsatscale
    targetRevision: HEAD
    path: ./app-of-apps/my-app-list/infrastructure-provisioning

    # directory
    directory:
      recurse: false
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with the following delays between attempts (5s, 10s, 20s, 40s, 80s); retry controlled using the `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing (false by default).
      selfHeal: true # Specifies if a partial app sync should be executed when resources are changed only in the target Kubernetes cluster and no git change is detected (false by default).
      allowEmpty: false # Allows deleting all application resources during automatic syncing (false by default).
